# Generated by Django 4.2.21 on 2025-05-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('appID', models.IntegerField(primary_key=True, serialize=False)),
                ('appName', models.CharField(blank=True, max_length=100, null=True)),
                ('appImage', models.URLField(blank=True, null=True)),
                ('releaseDate', models.CharField(blank=True, max_length=100, null=True)),
                ('isFree', models.BooleanField(blank=True, default=False, null=True)),
                ('developers', models.CharField(blank=True, max_length=100, null=True)),
                ('publishers', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('metacriticScore', models.IntegerField(blank=True, default=0, null=True)),
                ('recommendationCount', models.IntegerField(blank=True, default=0, null=True)),
                ('achievementCount', models.IntegerField(blank=True, default=0, null=True)),
                ('screenshotCount', models.IntegerField(blank=True, default=0, null=True)),
                ('requiredAge', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'AppInfo',
            },
        ),
        migrations.CreateModel(
            name='AppPredictedDiscountInfo',
            fields=[
                ('discountResultID', models.AutoField(primary_key=True, serialize=False)),
                ('predictedDiscountStart', models.DateTimeField(blank=True, null=True)),
                ('predictedDiscountPercents', models.IntegerField(blank=True, null=True)),
                ('appID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appinfo')),
            ],
            options={
                'db_table': 'AppPredictedDiscountInfo',
            },
        ),
        migrations.CreateModel(
            name='AppTagInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('appID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appinfo')),
            ],
            options={
                'db_table': 'AppTagInfo',
                'unique_together': {('tag', 'appID')},
            },
        ),
        migrations.CreateModel(
            name='AppPriorDiscountInfo',
            fields=[
                ('discountID', models.AutoField(primary_key=True, serialize=False)),
                ('discountStart', models.DateTimeField(blank=True, null=True)),
                ('discountEnd', models.DateTimeField(blank=True, null=True)),
                ('oldPrice', models.IntegerField()),
                ('newPrice', models.IntegerField()),
                ('discountPercents', models.IntegerField(blank=True, default=0, null=True)),
                ('currentlyDiscounted', models.BooleanField(blank=True, null=True)),
                ('appID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appinfo')),
            ],
            options={
                'db_table': 'AppPriorDiscountInfo',
                'unique_together': {('discountID', 'appID')},
            },
        ),
        migrations.CreateModel(
            name='AppGenreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('appID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appinfo')),
            ],
            options={
                'db_table': 'AppGenreInfo',
                'unique_together': {('genre', 'appID')},
            },
        ),
        migrations.CreateModel(
            name='AppCategoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('appID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appinfo')),
            ],
            options={
                'db_table': 'AppCategoryInfo',
                'unique_together': {('category', 'appID')},
            },
        ),
    ]
