# Generated by Django 4.2.21 on 2025-05-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appcategoryinfo',
            table='app_category_info',
        ),
        migrations.AlterModelTable(
            name='appgenreinfo',
            table='app_genre_info',
        ),
        migrations.AlterModelTable(
            name='appinfo',
            table='app_Info',
        ),
        migrations.AlterModelTable(
            name='apppredicteddiscountinfo',
            table='app_predicted_discount_info',
        ),
        migrations.AlterModelTable(
            name='apppriordiscountinfo',
            table='app_prior_discount_info',
        ),
        migrations.AlterModelTable(
            name='apptaginfo',
            table='app_tag_info',
        ),
    ]
