# Generated by Django 4.2.21 on 2025-05-29 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appcategoryinfo_table_alter_appgenreinfo_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinfo',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='appinfo',
            name='publishers',
        ),
        migrations.RemoveField(
            model_name='apppriordiscountinfo',
            name='currentlyDiscounted',
        ),
        migrations.AddField(
            model_name='appinfo',
            name='currentlyDiscounted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='appinfo',
            name='final_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='appinfo',
            name='init_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='AppPublishersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=20)),
                ('appID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appinfo')),
            ],
            options={
                'db_table': 'app_publishers_info',
                'unique_together': {('publisher', 'appID')},
            },
        ),
        migrations.CreateModel(
            name='AppDevelopersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(max_length=20)),
                ('appID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appinfo')),
            ],
            options={
                'db_table': 'app_developers_info',
                'unique_together': {('developer', 'appID')},
            },
        ),
    ]
