# Generated by Django 4.2.21 on 2025-05-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_appinfo_developers_remove_appinfo_publishers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinfo',
            name='price',
        ),
        migrations.AlterField(
            model_name='appcategoryinfo',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appdevelopersinfo',
            name='developer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appgenreinfo',
            name='genre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='achievementCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='currentlyDiscounted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='isFree',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='metacriticScore',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='recommendationCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='screenshotCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='apppublishersinfo',
            name='publisher',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='apptaginfo',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
