# Generated by Django 4.2.21 on 2025-05-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_appinfo_price_alter_appcategoryinfo_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apppriordiscountinfo',
            name='newPrice',
        ),
        migrations.RemoveField(
            model_name='apppriordiscountinfo',
            name='oldPrice',
        ),
        migrations.AlterField(
            model_name='apppriordiscountinfo',
            name='discountPercents',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
