# Generated by Django 4.2.21 on 2025-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_apppriordiscountinfo_newprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppredicteddiscountinfo',
            old_name='predictedDiscountPercents',
            new_name='predictedSalePercents',
        ),
        migrations.RemoveField(
            model_name='apppredicteddiscountinfo',
            name='predictedDiscountStart',
        ),
        migrations.AddField(
            model_name='apppredicteddiscountinfo',
            name='isWorthy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='apppredicteddiscountinfo',
            name='predictedDateLeft',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='apppredicteddiscountinfo',
            name='predictedDateMid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='apppredicteddiscountinfo',
            name='predictedDateRight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
